version: '3.8'

networks:
  network:
    external: true

volumes:
  mongo_data:

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB}
    ports:
      - '${MONGO_PORT}:27017'
    volumes:
      - mongo_data:/data/db
    networks:
      - network
